package appletprueba;

import java.awt.Graphics;
import javax.swing.JApplet;
import javax.swing.JOptionPane;

/**
 *
 * @author enrique
 */
public class SumaApplet extends JApplet {
    private double suma; // Suma de los valores ingresados por el usuario
    /**
     * Initializes the applet SumaApplet
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        String primerNumero; // primera cadena introducida por el usuario
        String segundoNumero; // segunda cadena introducida por el usuario
        double numero1; // primer número a sumar
        double numero2; // segundo número a sumar

        // obtiene el primer número del usuario
        primerNumero = JOptionPane.showInputDialog(
        "Escriba el primer valor de punto flotante");

        // obtiene el segundo número del usuario
        segundoNumero = JOptionPane.showInputDialog(
        "Escriba el segundo valor de punto flotante");

        // convierte los números del tipo String al tipo double
        numero1 = Double.parseDouble( primerNumero );
        numero2 = Double.parseDouble( segundoNumero );
        
        suma = numero1 + numero2; // suma los números
    }
    
    // dibuja los resultados en un rectángulo, en el fondo del applet
    @Override
    public void paint( Graphics g )
    {
        super.paint( g ); // llama a la versión del método paint de la superclase
        // dibuja un rectángulo empezando desde (15, 10), que tenga 270
        // píxeles de ancho y 20 píxeles de alto
        g.drawRect( 15, 10, 270, 20 );
        // dibuja los resultados como un objeto String en (25, 25)
        g.drawString( "La suma es " + suma, 25, 25 );
    } // fin del método paint

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
